.TH VIDEOMORPH "1" "Aug 2017" "Version 1.2" "VideoMorph"

.SH NAME
videomorph \- Small GUI Video Converter based on ffmpeg, Python 3 and Qt5.

.SH SYNOPSIS
.B videomorph [\-i INPUT-FILE [INPUT-FILE ...]] ... [\-d INPUT-DIR]

.SH DESCRIPTION
Small Video Converter based on ffmpeg, Python 3 and Qt5.
Unlike other video converters, VideoMorph focuses on a single goal:
make video conversion simple, with an easy to use GUI and allowing
the user to convert to the currently most popular video formats.
VideoMorph GUI is simple and clean focused on usability, eliminating
annoying options rarely used.
VideoMorph is a video converter, just that. If you want a video
editor, VideoMorph isn't for you.

.SH OPTIONS
.B Getting help:

.TP
.B -h, --help
Show a brief list of options.

.PP
.B Opening files:

.TP
.B -i, --input-file INPUT-FILE [INPUT-FILE ...]
Starts VideoMorph listing the video(s) in INPUT-FILE.

.TP
.B -d, --input-dir INPUT-DIR
Starts VideoMorph loading all the videos in INPUT-DIR and sub-directories (recursively).

.SH MAINTAINER
VideoMorph Development Team
.TP
- Ozkar L. Garcell -- Project leader
.TP
- Leodanis Pozo Ramos -- Main developer

.SH HOMEPAGE
.I https://github.com/codeshard/videomorph/

.SH REPORTING BUGS
For bug reports, please send an e-mail to:
.TP
Leodanis Pozo Ramos <lpozor78@gmail.com>
