.TH VIDEOMORPH "1" "Jul 2020" "Version 1.5 Canelo" "VideoMorph"

.SH NAME
videomorph \- Video Converter based on ffmpeg, Python 3 and PyQt6.

.SH SYNOPSIS
.B videomorph [\-i INPUT-FILE [INPUT-FILE ...]] ... [\-d INPUT-DIR]

.SH DESCRIPTION
Video Converter based on ffmpeg, Python 3 and PyQt6.
Unlike other video converters, VideoMorph focuses on a single goal:
make video conversion simple, with an easy to use GUI and allowing
the user to convert to the currently most popular video formats.
VideoMorph GUI is simple and clean focused on usability, removing
annoying options rarely used.
VideoMorph is a video converter, just that. If you want a video
editor, VideoMorph isn't for you.

.SH OPTIONS
.B Getting help:

.TP
.B -h, --help
Show a brief list of options.

.PP
.B Opening files:

.TP
.B -i, --input-file INPUT-FILE [INPUT-FILE ...]
Starts VideoMorph listing the video(s) in INPUT-FILE.

.TP
.B -d, --input-dir INPUT-DIR
Starts VideoMorph loading all the videos in INPUT-DIR and sub-directories (recursively).

.SH MAINTAINER
VideoMorph Development Team
.TP
- Leodanis Pozo Ramos -- Main developer
.TP
- Ozkar L. Garcell -- Project creator

.SH HOMEPAGE
.I https://github.com/videomorph-dev/videomorph/

.SH REPORTING BUGS
For bug reports, please fill an issue:
.TP
.I https://github.com/videomorph-dev/videomorph/issues
